### ISSUE TITLE
Padrão de projeto

### ISSUE THREAD

**Issue by joaovsoliveira** [MC426-2s2023/MC426#47]
# Componente: Sistema de Notificações

Para a implantação do sistema de notificações baseado na proximidade do usuário a uma região de ocorrência foi utilizado um observer que monitora por alterações da posição do usuário e a compara com as posições no banco de dados a um determinado raio deste.

Com isso, no contexto do projeto, o Publisher se trata do model LocationProfile e o Subscriber da classe Warnig. Desta forma, um objeto da classe LocationProfile associado a um usuário notifica um objeto da classe Warning quando os dados de Latitude e Longitude do Usuário são modificados.

``` python
# OneToOne link para usuario padrao do Django
class LocationProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key = True, related_name = "location_profile")
	user_lat = models.DecimalField("latitude", max_digits=10, decimal_places=6)
	user_lng = models.DecimalField("longitude", max_digits=10, decimal_places=6)
	subs = [Warning()]

	def subscribe(self, newSub):
    	    self.subs.append(newSub)

	def updateUserLocation(self, request, lat, lng):
    	    if self.user_lat == lat and self.user_lng == lng: # posicao nao foi alterada
        	return

    	    self.user_lat, self.user_lng = lat,lng
    	    self.save(update_fields=['user_lat', 'user_lng'])

    	    for subscriber in self.subs:
                subscriber.update(request, lat, lng)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
         LocationProfile.objects.create(user=instance, user_lat=0, user_lng=0)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.location_profile.save()

```

O Subscriber, por sua vez, ao receber a informação da posição atual do usuário busca no banco de dados por ocorrências em um determinado raio desta nova posição, caso venha a encontrar alguma, ele envia uma notificação com a informação da distância até a ocorrência mais próxima do usuário.

```python
class Warning:
	def setMsg(self, msg_head, msg_body):
    	    self.msg = {
        	"head": msg_head,
        	"body": msg_body,
    	    }

	def warnUser(self, request, userPosition):
    	    radius = 30
    	    regProx = crimeRegisterProximity(userPosition[0], userPosition[1], radius)
    	    if regProx: # existe alguma ocorrencia proxima
        	self.setMsg("Atencao!",  "Existe uma ocorrencia ha {x} metros de voce".format(x = regProx[0][1]))
        	send_user_notification(user=request.user, payload=self.msg, ttl=1000)
    	    return

	def update(self, request, lat, lng):
    	    self.warnUser(request, [lat, lng])	 
```

## Diagrama

![diagram](https://github.com/MC426-2s2023/MC426/assets/142899966/8a181650-b054-4006-a503-1dc63c9ca40f)

**Comment by joaovsoliveira** [comment]
@brenofranca83 um dos integrantes do grupo acabou por atualizar a branch 'develop' localmente com base na 'feature/notification' e subiu os commits diretamente na 'develop'. Por isso não foi possível linkar um PR com as alterações, apenas conseguimos linkar a branch. Lá é possível visualizar os commits que contém o padrão de projeto adotado.

**Comment by brenofranca83** [comment]
> @brenofranca83 um dos integrantes do grupo acabou por atualizar a branch 'develop' localmente com base na 'feature/notification' e subiu os commits diretamente na 'develop'. Por isso não foi possível linkar um PR com as alterações, apenas conseguimos linkar a branch. Lá é possível visualizar os commits que contém o padrão de projeto adotado.

Ok, encontrei
